alias tls='tmux ls'
alias tat='tmux attach -t'
alias tns='tmux new-session -s'
alias tks='tmux kill-server'
alias tad='tmux attach -d -t'
alias tkst='tmux kill-session -t'
alias tm='tmux new-session -t r00t'