#!/bin/sh

# Set bash as our shell, idk why anyone would use something else ;)
shell="$(which bash)"
export SHELL="$shell"

# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"
export PATH="$HOME/gems/bin:$PATH"

# Vim for life
export EDITOR=/bin/vim

# Color prompt
export TERM=xterm-256color

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Get color support for 'less'
export LESS="--RAW-CONTROL-CHARS"

# make man have color
#shellcheck disable=SC2155
export LESS_TERMCAP_mb="$(tput bold; tput setaf 2)" # green
#shellcheck disable=SC2155
export LESS_TERMCAP_md="$(tput bold; tput setaf 6)" # cyan
#shellcheck disable=SC2155
export LESS_TERMCAP_me="$(tput sgr0)"
#shellcheck disable=SC2155
export LESS_TERMCAP_so="$(tput bold; tput setaf 3; tput setab 4)" # yellow on blue
#shellcheck disable=SC2155
export LESS_TERMCAP_se="$(tput rmso; tput sgr0)"
#shellcheck disable=SC2155
export LESS_TERMCAP_us="$(tput smul; tput bold; tput setaf 7)" # white
#shellcheck disable=SC2155
export LESS_TERMCAP_ue="$(tput rmul; tput sgr0)"
#shellcheck disable=SC2155
export LESS_TERMCAP_mr="$(tput rev)"
#shellcheck disable=SC2155
export LESS_TERMCAP_mh="$(tput dim)"
#shellcheck disable=SC2155
export LESS_TERMCAP_ZN="$(tput ssubm)"
#shellcheck disable=SC2155
export LESS_TERMCAP_ZV="$(tput rsubm)"
#shellcheck disable=SC2155
export LESS_TERMCAP_ZO="$(tput ssupm)"
#shellcheck disable=SC2155
export LESS_TERMCAP_ZW="$(tput rsupm)"
export GROFF_NO_SGR=1         # For Konsole and Gnome-terminal
